name: SkyFightSystem
author: TGM_Nick
version: 1.7.1.0
main: com.CoreSkySystem.Main.Main

commands:
   ts:
     description: Zeigt unsere Team Speak 3 IP an
   skype:
     description: Zeigt die Skype namen an
   epic:
     description: Alle Infos zum Spendenrang Epic
   premium:
     description: Alle Infos zum Spendenrang Premium
   spenden:
     description: Zeigt dir, wie du spenden kannst
   regeln:
     description: Zeigt dir unsere Server regeln
   hilfe:
     description: Zeigt dir alle wichtigen Befehle
   ja:
     description: Stimme für ja ab 
   nein:
     description: Stimme für nein ab
   umfrage:
     description: starte eine abstimm aktion
   copyright:
     description: COPYRIGHT BY SKYFIGHT.CH
   ultimate:
     description: Alle Infos zum Spendenrang Ultimate
   setmotd:
     description: Set the motd of the server.
     usage: /setmotd (motd)
     aliases: sm
   report:
     description: Report a player
     usage: /report (player) (reason)
   team:
     description: zeigt dir das Team
   warn:
     description: Verwarne andere Spieler
     usage: /warn (Player) (reason)
     aliases: wa
   clearwarn:
     description: Loesche alle Verwarnungen eines Spielers
     usage: /clearwarn (Player)
   clearchat:
     description: Leert den Chat!
     usage: /cc
     aliases: cc
   gamemode:
     description: Changes your Gamemode
     usage: /gm (player)
     aliases: gm
   chat:
     description: Chatte im Namen eines anderen Spielers
     usage: /chat (player) (message)
     aliases: ch
   giveall:
     description: Gib allen Online - Spielern ein bestimmtes Item
     usage: /giveall (itemid) (anzahl)
     aliases: ga
   noarmor:
     description: Entferne einem Spieler seine Ruestung
     usage: /noarmor (player)
     aliases: na
   cenchant:
     description: Enchante das Item in deiner Hand
     usage: /cenchant (enchantment) (level)
     aliases: ce
   globalmute:
     description: Lass niemanden mehr chatten
     usage: /globalmute
     aliases: /gm
   rename:
     description: Benenne dein Item um
     usage: /rename (name)
     aliases: ren
   hkick:
     description: Kicke einen Spieler ausnahmslos
     usage: /hkick (player)
     aliases: hk
   hban:
     description: Banne einen Spieler ausnahmslos
     usage: /hban (player)
     aliases: hb
   cvanish:
     description: Verstecke dich vor allen Spielern auf dem Server
     usage: /cvanish
     aliases: cv
   armor:
     description: Gib einem Spieler eine Ruestung aus einem Material deiner Wahl
     usage: /armor (player) (material)
   skyfight:
     description: Bekomme eine Liste aller Commands
     usage: /skyfight
     aliases: sf
   sk:
     description: Mache einen Rundruf
   kit:
     description: Öffte dir Kit auswahl